pipeline
        {
            agent { dockerfile true }
            environment {
                CI = 'true'
            }
            stages {
                stage('Build') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('Test') {
                    steps {
                        sh 'chmod +x scripts/run-tests.sh'
                    }
                }
            }
            post {
                always {
                    junit 'build/reports/**/*.xml'
                }
            }
        }
